import { IActionDescription } from "action/IAction";
import { IItemTypeGroup, ItemType, ItemTypeGroup } from "Enums";
import { IGroupDescription, IItemDescription, IRecipeComponent } from "item/IItem";
export declare const itemDescriptions: SaferDescription<IItemDescription>;
export default itemDescriptions;
export declare const itemGroups: Description<IGroupDescription>;
export declare const itemActionDescriptions: SaferDescription<IActionDescription>;
export declare function RecipeComponent(type: (ItemType | ItemTypeGroup), requiredAmount: number, consumedAmount: number, disassembleAmount?: number, ignoreWeight?: boolean): IRecipeComponent;
export declare function ExtendItem(typeOrItemDescription: ItemType | Partial<IItemDescription>, extendWith: Partial<IItemDescription>): Description<IItemDescription>;
export declare function isItemTypeGroup(itemType: ItemType | ItemTypeGroup | IItemTypeGroup): itemType is ItemTypeGroup;
export declare function isCustomItemTypeGroup(itemType: ItemType | ItemTypeGroup | IItemTypeGroup): itemType is IItemTypeGroup;
export declare function isItemTypeInGroup(itemType: ItemType, itemGroupSearch: ItemTypeGroup | IItemTypeGroup): boolean;
