declare type nullable = undefined | null;
interface Function {
    bind<F extends () => R, R>(this: F, thisArg?: F | nullable): () => R;
    bind<R>(this: new () => R, thisArg?: nullable): () => R;
    bind<F extends (_0: _A) => R, _A, R>(this: F, thisArg?: F | nullable): (_0: _A) => R;
    bind<F extends (_0: _A) => R, _A, R>(this: F, thisArg: F | nullable, _0: _A): () => R;
    bind<_A, R>(this: new (_0: _A) => R, thisArg?: nullable): (_0: _A) => R;
    bind<_A, R>(this: new (_0: _A) => R, thisArg: nullable, _0: _A): () => R;
    bind<F extends (_0: _A, _1: _B) => R, _A, _B, R>(this: F, thisArg?: F | nullable): (_0: _A, _1: _B) => R;
    bind<F extends (_0: _A, _1: _B) => R, _A, _B, R>(this: F, thisArg: F | nullable, _0: _A): (_1: _B) => R;
    bind<F extends (_0: _A, _1: _B) => R, _A, _B, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B): () => R;
    bind<_A, _B, R>(this: new (_0: _A, _1: _B) => R, thisArg?: nullable): (_0: _A, _1: _B) => R;
    bind<_A, _B, R>(this: new (_0: _A, _1: _B) => R, thisArg: nullable, _0: _A): (_1: _B) => R;
    bind<_A, _B, R>(this: new (_0: _A, _1: _B) => R, thisArg: nullable, _0: _A, _1: _B): () => R;
    bind<F extends (_0: _A, _1: _B, _2: _C) => R, _A, _B, _C, R>(this: F, thisArg?: F | nullable): (_0: _A, _1: _B, _2: _C) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C) => R, _A, _B, _C, R>(this: F, thisArg: F | nullable, _0: _A): (_1: _B, _2: _C) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C) => R, _A, _B, _C, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B): (_2: _C) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C) => R, _A, _B, _C, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C): () => R;
    bind<_A, _B, _C, R>(this: new (_0: _A, _1: _B, _2: _C) => R, thisArg?: nullable): (_0: _A, _1: _B, _2: _C) => R;
    bind<_A, _B, _C, R>(this: new (_0: _A, _1: _B, _2: _C) => R, thisArg: nullable, _0: _A): (_1: _B, _2: _C) => R;
    bind<_A, _B, _C, R>(this: new (_0: _A, _1: _B, _2: _C) => R, thisArg: nullable, _0: _A, _1: _B): (_2: _C) => R;
    bind<_A, _B, _C, R>(this: new (_0: _A, _1: _B, _2: _C) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C): () => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D) => R, _A, _B, _C, _D, R>(this: F, thisArg?: F | nullable): (_0: _A, _1: _B, _2: _C, _3: _D) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D) => R, _A, _B, _C, _D, R>(this: F, thisArg: F | nullable, _0: _A): (_1: _B, _2: _C, _3: _D) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D) => R, _A, _B, _C, _D, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B): (_2: _C, _3: _D) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D) => R, _A, _B, _C, _D, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C): (_3: _D) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D) => R, _A, _B, _C, _D, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D): () => R;
    bind<_A, _B, _C, _D, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D) => R, thisArg?: nullable): (_0: _A, _1: _B, _2: _C, _3: _D) => R;
    bind<_A, _B, _C, _D, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D) => R, thisArg: nullable, _0: _A): (_1: _B, _2: _C, _3: _D) => R;
    bind<_A, _B, _C, _D, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D) => R, thisArg: nullable, _0: _A, _1: _B): (_2: _C, _3: _D) => R;
    bind<_A, _B, _C, _D, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C): (_3: _D) => R;
    bind<_A, _B, _C, _D, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D): () => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, _A, _B, _C, _D, _E, R>(this: F, thisArg?: F | nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, _A, _B, _C, _D, _E, R>(this: F, thisArg: F | nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, _A, _B, _C, _D, _E, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, _A, _B, _C, _D, _E, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, _A, _B, _C, _D, _E, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, _A, _B, _C, _D, _E, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): () => R;
    bind<_A, _B, _C, _D, _E, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, thisArg?: nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R;
    bind<_A, _B, _C, _D, _E, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, thisArg: nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E) => R;
    bind<_A, _B, _C, _D, _E, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, thisArg: nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E) => R;
    bind<_A, _B, _C, _D, _E, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E) => R;
    bind<_A, _B, _C, _D, _E, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E) => R;
    bind<_A, _B, _C, _D, _E, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): () => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, _A, _B, _C, _D, _E, _F, R>(this: F, thisArg?: F | nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, _A, _B, _C, _D, _E, _F, R>(this: F, thisArg: F | nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, _A, _B, _C, _D, _E, _F, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E, _5: _F) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, _A, _B, _C, _D, _E, _F, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E, _5: _F) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, _A, _B, _C, _D, _E, _F, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E, _5: _F) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, _A, _B, _C, _D, _E, _F, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): (_5: _F) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, _A, _B, _C, _D, _E, _F, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F): () => R;
    bind<_A, _B, _C, _D, _E, _F, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, thisArg?: nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R;
    bind<_A, _B, _C, _D, _E, _F, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, thisArg: nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R;
    bind<_A, _B, _C, _D, _E, _F, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, thisArg: nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E, _5: _F) => R;
    bind<_A, _B, _C, _D, _E, _F, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E, _5: _F) => R;
    bind<_A, _B, _C, _D, _E, _F, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E, _5: _F) => R;
    bind<_A, _B, _C, _D, _E, _F, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): (_5: _F) => R;
    bind<_A, _B, _C, _D, _E, _F, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F): () => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, _A, _B, _C, _D, _E, _F, _G, R>(this: F, thisArg?: F | nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, _A, _B, _C, _D, _E, _F, _G, R>(this: F, thisArg: F | nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, _A, _B, _C, _D, _E, _F, _G, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, _A, _B, _C, _D, _E, _F, _G, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E, _5: _F, _6: _G) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, _A, _B, _C, _D, _E, _F, _G, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E, _5: _F, _6: _G) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, _A, _B, _C, _D, _E, _F, _G, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): (_5: _F, _6: _G) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, _A, _B, _C, _D, _E, _F, _G, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F): (_6: _G) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, _A, _B, _C, _D, _E, _F, _G, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G): () => R;
    bind<_A, _B, _C, _D, _E, _F, _G, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, thisArg?: nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, thisArg: nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, thisArg: nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E, _5: _F, _6: _G) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E, _5: _F, _6: _G) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): (_5: _F, _6: _G) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F): (_6: _G) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G): () => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg?: F | nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg: F | nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): (_5: _F, _6: _G, _7: _H) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F): (_6: _G, _7: _H) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G): (_7: _H) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, _A, _B, _C, _D, _E, _F, _G, _H, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H): () => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg?: nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg: nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg: nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E, _5: _F, _6: _G, _7: _H) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): (_5: _F, _6: _G, _7: _H) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F): (_6: _G, _7: _H) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G): (_7: _H) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H): () => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg?: F | nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): (_5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F): (_6: _G, _7: _H, _8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G): (_7: _H, _8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H): (_8: _I) => R;
    bind<F extends (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, _A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: F, thisArg: F | nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I): () => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg?: nullable): (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A): (_1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A, _1: _B): (_2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C): (_3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D): (_4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E): (_5: _F, _6: _G, _7: _H, _8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F): (_6: _G, _7: _H, _8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G): (_7: _H, _8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H): (_8: _I) => R;
    bind<_A, _B, _C, _D, _E, _F, _G, _H, _I, R>(this: new (_0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I) => R, thisArg: nullable, _0: _A, _1: _B, _2: _C, _3: _D, _4: _E, _5: _F, _6: _G, _7: _H, _8: _I): () => R;
}
