import IAudio from "audio/IAudio";
import IResourceLoader from "IResourceLoader";
import INotifier from "renderer/INotifier";
import IWorldRenderer from "renderer/IWorldRenderer";
import { IParticle } from "renderer/particle/IParticle";
export declare const resourceLoader: IResourceLoader;
export declare const audio: IAudio;
export declare const notifier: INotifier;
export declare const particle: IParticle;
export declare const worldRenderer: IWorldRenderer;
