import { IPlayOptions } from "game/IGame";
import { ModState } from "mod/IModManager";
import { IPlayerCustomization } from "player/IPlayer";
import BaseScreen from "ui/screens/BaseScreen";
export default class TitleScreen extends BaseScreen {
    openedMenus: string[];
    elementAboutContainer: JQuery;
    elementChangelogContainer: JQuery;
    elementChangelogLoading: JQuery;
    elementChangelogList: JQuery;
    elementChangelogSwitcherTemplate: JQuery;
    elementCharacterContainer: JQuery;
    elementCharacterHairColor: JQuery;
    elementCharacterImportInput: JQuery;
    elementCharacterPreview: JQuery;
    elementCharacterPreviewHairFilter: JQuery;
    elementCharacterPreviewHairLayers: JQuery;
    elementCharacterPreviewLayers: JQuery;
    elementCharacterPreviewSkinFilter: JQuery;
    elementCharacterSkinColor: JQuery;
    elementCharacterSwatchTemplate: JQuery;
    elementEndGameHeaderBottom: JQuery;
    elementEndGameHighscore: JQuery;
    elementHighscores: JQuery;
    elementHighscoresContainer: JQuery;
    elementHighscoresNoHighscores: JQuery;
    elementHighscoreTemplate: JQuery;
    elementImportGameInput: JQuery;
    elementInternalMods: JQuery;
    elementInternalModsContainer: JQuery;
    elementJoinGameContainer: JQuery;
    elementJoinGameServerName: JQuery;
    elementLocalMods: JQuery;
    elementLocalModsContainer: JQuery;
    elementModContainer: JQuery;
    elementModsNone: JQuery;
    elementModTemplate: JQuery;
    elementNewGameContainer: JQuery;
    elementPlayGameContainer: JQuery;
    elementPlayGameSeparater: JQuery;
    elementSavedGameTemplate: JQuery;
    elementWorkshopMods: JQuery;
    elementWorkshopModsContainer: JQuery;
    private hairstyleImageCache;
    selector(): string;
    bindElements(): void;
    updateClickableLeechList(): void;
    unbindElements(): void;
    onShow(showOptions?: any): void;
    onHide(): void;
    onKeyDown(event: JQueryEventObject, keyCode: number, blockable: boolean): boolean | null;
    getOpenedMenu(): string;
    isMenuOpen(menu: string): boolean;
    showMainMenuId(mainMenuId: string): void;
    refreshSlots(): void;
    refreshMods(): void;
    refreshHighscoresMenu(tab?: "All" | "Normal" | "DailyChallenge"): void;
    updateModState(element: JQuery, id: number): void;
    setAllModStates(state: ModState): void;
    postUpdateModState(): void;
    updateHairstyle(): void;
    onAction(actionId: string, element: JQuery): void;
    updateCharacterPreviewColors(colorType: string): void;
    actionStartNewGame(): void;
    actionJoinGame(): void;
    actionEditGame(slot: number, inputElement: JQuery): void;
    actionContinueGame(slot: number): void;
    playSlot(slot: number, options?: IPlayOptions): void;
    actionDeleteGame(slot: number): void;
    getTooltipHtml(element: JQuery): string;
    onImportCharacter(result: string): any;
    onImportGame(result: string): any;
    onSlotNameChange(slot: number, inputElement: JQuery): void;
    refreshNewGame(): void;
    refreshJoinGame(): void;
    refreshCharacterCustomization(customization?: IPlayerCustomization): void;
    refreshEndGame(): void;
    exportToFile(slot: number): void;
    exportToSteamWorkshop(name: string, slot: number): void;
    private refreshChangelogMenu();
    private loadChangelog(version?);
    private appendChangelog(title, cards?);
    private appendModChangelog(cards?);
}
