import { ModType } from "mod/IModManager";
import { ISteamId, ISteamworks, IWorkshopItem } from "steamworks/ISteamworks";
export default class Steamworks implements ISteamworks {
    private installDir;
    private greenworks;
    private ipc;
    private shell;
    private os;
    private webFrame;
    private remote;
    private path;
    private electron;
    private winston;
    private fileSystem;
    private ua;
    private uaReporter;
    private recordedProblems;
    private steamId;
    private betaName;
    private overlayWorks;
    private platform;
    private initializingMods;
    private logsPath;
    private logFilePath;
    private multiplayerLogFilePath;
    private modsPath;
    private workshopPath;
    private workshopModsPath;
    private workshopSyncPath;
    private workshopSharePath;
    private loadedMods;
    private publishedMods;
    private workshopUrl;
    private workshopFileUrl;
    private ignoredDirectories;
    private _serverIdToJoin;
    isElectron(): boolean;
    isOverlayWorking(): boolean;
    isGreenworksEnabled(): boolean;
    getAbsolutePath(p: string): any;
    isLinux(): boolean;
    initialize(): void;
    onUnload(): void;
    setOverlayWorks(overlayWorks: boolean): void;
    setupMods(callback: () => void): void;
    getSteamId(): ISteamId;
    getScreenName(): string | undefined;
    getBetaName(): string;
    getPublishedMods(): IWorkshopItem[];
    setRichPresence(key: string, value: string): boolean;
    clearRichPresence(): void;
    getPublishedMod(publishFileId: string): IWorkshopItem | undefined;
    fillOutWorkshopMod(index: number, item?: IWorkshopItem): void;
    publishMod(modIndex: number, callback: (err?: string, publishedFileId?: string) => void): void;
    createArchive(id: string, source: string, callback: (err?: string) => void): void;
    getPublishedItems(callback: (err: string | undefined, items?: IWorkshopItem[]) => void): void;
    openUrl(url: string): void;
    openWorkshop(publishId?: string): void;
    openModsFolder(): void;
    openLogsFolder(): void;
    unsubscribe(publishId: string, callback: (err?: string) => void): void;
    sendMessage(name: string, data: string): void;
    toggleDeveloperTools(): void;
    getModPath(name: string, modType: ModType, file?: string, checkIfExists?: boolean): string | undefined;
    createSaveGameMod(name: string, slot: number, callback: (success: boolean) => void): void;
    deleteSaveGameMod(name: string): void;
    debugLog(...args: any[]): void;
    addZoomFactor(change: number): void;
    setDefaultZoomFactor(): void;
    updateZoomFactor(): void;
    onUpdateZoomFactor(): void;
    hasServerToJoin(): boolean;
    onReady(): void;
    setupReporting(): void;
    recordProblem(message: string): void;
    setupMultiplayerLog(): void;
    multiplayerLog(...args: any[]): void;
    multiplayerLogSkipConsole(...args: any[]): void;
    multiplayerLogError(...args: any[]): void;
    private appendToMultiplayerLog(...args);
    private setupAndInitializeWorkshopMods(callback, retried?);
    private initializeModsFromFolder(folderName, modType, callback);
    private enumerateInstalledWorkshopMods(callback);
    private refreshSetupMods();
    private refreshPublishedMods(callback);
    private getIdFromWorkshopItem(item);
    private syncWorkshopItems(callback);
    private copyFolder(source, destination, callback);
    private saveFilesToCloud(id, callback);
    private getFileShareId(id, callback);
    private publishFileToWorkshop(id, title, description, publishedFileId, callback);
    private extractArchive(id, destination, callback);
    private safeOpenFolder(folder);
    private onGameOverlayActive(isActive, callback?);
    private onGameJoinRequested(connectionString);
    private createFolderIfNotExists(folder);
    private getSyncPath(name);
    private getSharePathForModZip(name);
    private getSharePathForModImage(name);
    private recordEvent(categorySuffix, action);
    private parseConnectArgument(arg);
}
