import Vec2 = TSM.vec2;
import { IPlayer } from "player/IPlayer";
import IFieldOfView from "renderer/fieldofview/IFieldOfView";
import ITextureDebugRenderer from "renderer/ITextureDebugRenderer";
import { CompiledProgram } from "renderer/Shaders";
import { Bound3 } from "Utilities";
export default class FieldOfView implements IFieldOfView {
    private gl;
    radius: number;
    private subdivisions;
    hBlurProgram: CompiledProgram;
    vBlurProgram: CompiledProgram;
    maxRadius: number;
    texLight: WebGLTexture;
    texLightOld: WebGLTexture;
    disabled: boolean;
    blurEnabled: boolean;
    computeOffset: Vec2;
    private shaderProgram;
    private debugRenderer;
    private texLight01;
    private texLight02;
    private texBlurStorage;
    private framebuffer1;
    private framebuffer2;
    private viewQuadBuffer;
    private seed;
    compileShaders(gl: WebGLRenderingContext): void;
    constructor(gl: WebGLRenderingContext, radius: number, subdivisions?: number);
    getTextureSize(): number;
    getSubdivisions(): number;
    tickSeed(): void;
    compute(lightBlocking?: boolean): void;
    createDebugRenderer(): ITextureDebugRenderer;
    getRadiusModifier(tileX: number, tileY: number): number;
    canAnyPlayerSeeTile(tileX: number, tileY: number, tileZ: number): boolean;
    canPlayerSeeTile(player: IPlayer, tileX: number, tileY: number, tileZ: number): boolean;
    getPlayersThatSeeTile(tileX: number, tileY: number, tileZ: number): IPlayer[];
    getBounds(player: IPlayer): Bound3;
    private updateExplored();
    private computeLights();
    private bresenham(x0, y0, x1, y1, z);
    private getLightSourceAt(worldX, worldY);
}
