import { TerrainType } from "Enums";
import { TileTemplateType } from "tile/ITerrain";
export declare function hasFinishedLoading(): boolean;
export declare function setFinishedLoading(): void;
export declare function clearFinishedLoading(): void;
export declare function spawnHouseItem(x: number, y: number, z: number): void;
export declare function spawnShoreItem(x: number, y: number, z: number): void;
export declare function spawnDoodad(tileType: TerrainType, x: number, y: number, z: number, afterMapGen?: boolean): void;
export declare function spawnTemplate(templateType: TileTemplateType, x: number, y: number, z: number): void;
export declare function loadDifferences(): void;
