import { DoodadType, TerrainType } from "Enums";
import * as Terrain from "tile/ITerrain";
export declare function hasFinishedLoading(): boolean;
export declare function setFinishedLoading(): void;
export declare function clearFinishedLoading(): void;
export declare function spawnHouseItem(x: number, y: number, z: number): void;
export declare function spawnShoreItem(x: number, y: number, z: number): void;
export declare function spawnDoodad(tileType: TerrainType, x: number, y: number, z: number, afterMapGen?: boolean): void;
export declare function spawnTileEvent(x: number, y: number, z: number): void;
export declare function spawnTemplate(templateType: Terrain.TileTemplateType, x: number, y: number, z: number): void;
export declare function setTileUnderDoodad(tile: Terrain.ITile, x: number, y: number, doodadType: DoodadType, addTileData?: boolean): void;
export declare function setupTiles(tileGenArray: Uint16Array): void;
export declare function loadDifferences(): void;
